### ISSUE TITLE
Signing a message with Bitcoin address?

### ISSUE THREAD

**Issue by lf94** [digitalbitbox/bitbox02-api-js#35]
Bity SA would love to support BitBox02, but it appears only message signing is possible with Ethereum. Does BitBox02 have the ability to do message signing for Bitcoin addresses? Really this is a huge blocker for us. We use it as a way to verify users own the wallet address.

**Comment by x1ddos** [comment]
> it appears only message signing is possible with Ethereum

The API does provide BTC message signing using `btcSignMessage` in https://github.com/digitalbitbox/bitbox02-api-js/blob/a58014f/src/bitbox02.js#L272-L296.

Or did you mean something else?

**Comment by lf94** [comment]
Ah, nope. I must've looked right over it then - thank you for pointing it out!

**Comment by lf94** [comment]
For what it's worth, the documentation fails to mention this method: https://github.com/digitalbitbox/bitbox02-api-js/blob/master/docs/methods.md
