### ISSUE TITLE
Get the last unused address from an xpub key

### ISSUE THREAD

**Issue by lf94** [digitalbitbox/bitbox02-api-js#36]
It would be very useful to request from the wallet the next unused address from an xpub key derivation. Otherwise the only other way to request the wallet do something is with the first account using the first address. Maybe the BitBoxBridge can query a blockchain explorer which BitBox owns?

**Comment by lf94** [comment]
For now I'm going with the solution that has so far worked for all wallets: use the 1st address of the 1st account.

**Comment by benma** [comment]
This library is merely a lib to communicate with the BitBox02, it does not contain full wallet functionality such as syncing accounts/addresses.

The bridge is also merely a communication bridge, currently there are no plans to add wallet functionality there - though it could definitely be useful.

Alternatively, you could extract the account xpub and then use your own backend to process it.

I will close this `wontfix`, as it is out of scope for this library.
