### ISSUE TITLE
Why btcDisplayAddressSimple doesn't return the address?

### ISSUE THREAD

**Issue by lf94** [digitalbitbox/bitbox02-api-js#39]
The documentation says `btcDisplayAddressSimple` will display the address on the device, but why not also return it to the caller? Otherwise I have to include extra code to derive the address after obtaining the xpub from calling `btcXPub`.

I imagine there is probably some explanation for this design, but I think it should be reconsidered!

**Comment by lf94** [comment]
In the meantime using https://www.npmjs.com/package/bip32 seems sufficient.

**Comment by benma** [comment]
This function does in fact also return the address.

`const address = await device.api.btcDisplayAddressSimple(...)`.

**Comment by lf94** [comment]
@benma ah, then the documentation is outdated. Thank you for clarifying!
