### ISSUE TITLE
TypeError: Cannot assign to read only property '0' of object '[object String]' when calling btcDisplayAddressSimple

### ISSUE THREAD

**Issue by lf94** [digitalbitbox/bitbox02-api-js#42]
Simply put, this is the call causing issues:

``` 

        const BTC_BECH32_1ST_ADDRESS_PATH = "m/84'/0'/0'/0/0";

        return this.client.btcDisplayAddressSimple(
          constants.messages.BTCCoin.BTC,
          BTC_BECH32_1ST_ADDRESS_PATH,
          constants.messages.BTCScriptConfig_SimpleType.P2WPKH,
        );
```

**Comment by thisconnect** [comment]
Yes I think the doc is out of date sorry for that. I believe the function doesn't return an object with the result, but a promise.

In your example you return the promise, so in place where you call this function you have to either use `await` or `.then()` depending on your preference.

```js 
const address = await this.client.btcDisplayAddressSimple(/* your args */)
// or

this.client.btcDisplayAddressSimple(/* your args */)
  .then(address => console.log(`got ${address}`))
  .catch(error => console.error(error.Message))
```

I'll look into it today and make a PR to fix the docs and mention it later in this issue. Sorry for the inconvenience.

**Comment by thisconnect** [comment]
Found an issue, instead of just "m/84'/0'/0'/0/0" you'll need:

```js
import {  getKeypathFromString } from 'bitbox02-api';

const BTC_BECH32_1ST_ADDRESS_PATH = getKeypathFromString("m/84'/0'/0'/0/0");
```

**Comment by lf94** [comment]
That's the real issue here yes. I know I was just returning the promise in the first comment :slightly_smiling_face: Big thank you @thisconnect !
