### ISSUE TITLE
ethDisplayAddress does not return address

### ISSUE THREAD

**Issue by lf94** [digitalbitbox/bitbox02-api-js#44]
https://github.com/digitalbitbox/bitbox02-api-js/blob/c8be6a495f847bedcaaf3291f279e4dc86010e13/src/bitbox02.js#L391

But btcDisplayAddressSimple does...

**Comment by thisconnect** [comment]
Comming 😬   in https://github.com/digitalbitbox/bitbox02-api-js/pull/40 I'll try to publich a new release today.

**Comment by lf94** [comment]
Excellent, thank you! Bity should have BitBox02 support released then by end of week.

**Comment by thisconnect** [comment]
published bitbox02-api@0.8.1, this should be fixed with the newest version.

**Comment by lf94** [comment]
Giving a go now.

**Comment by lf94** [comment]
Works! Thank you @thisconnect . See you around :wink:
